import random,string

##autogenerated edp_id 
def id_generator(size=10, chars=string.ascii_uppercase + string.digits): ##autogenerated ID
        return ''.join(random.choice(chars) for _ in range(size))