# Generated by Django 5.1.4 on 2024-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[(1, 'buy'), (2, 'sell')], max_length=10)),
            ],
        ),
    ]
