# Generated by Django 5.1.4 on 2025-01-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pay_name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('online', 'Online')], max_length=10)),
                ('amount', models.IntegerField()),
                ('pay_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=120)),
                ('pro_price', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('supp_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('sell_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sell_name', models.CharField(max_length=120)),
                ('sell_quantity', models.IntegerField()),
                ('sell_date', models.DateField()),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.payment')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sto_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Buy'), ('2', 'Sold')], max_length=5)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('sell_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.sell_product')),
                ('supp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Product',
            fields=[
                ('buy_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('buy_quantity', models.IntegerField()),
                ('buy_date', models.DateField()),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.payment')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('supp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
            ],
        ),
    ]
