# Generated by Django 5.1.4 on 2025-01-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='supp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.supplier'),
            preserve_default=False,
        ),
    ]
