# Generated by Django 5.1.4 on 2024-12-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_buyer_alter_product_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Buy_Product',
            fields=[
                ('supp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('buy_quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('pro_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('sell_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sell_quantity', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('pro_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=120)),
                ('sell_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='stock.sell_product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=120)),
                ('supp_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='stock.buy_product')),
            ],
        ),
    ]
