# Generated by Django 5.1.4 on 2025-01-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='pay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.payment'),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='pay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.payment'),
        ),
    ]
