# Generated by Django 5.1.4 on 2025-01-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_buy_product_pay_id_alter_sell_product_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sell_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='buy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.buy_product'),
        ),
    ]
