# Generated by Django 5.1.4 on 2025-01-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_product_crt_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='supp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.supplier'),
        ),
    ]
