# Generated by Django 5.1.4 on 2025-01-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_payment_supp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='supp_id',
            new_name='sell_id',
        ),
    ]
