# Generated by Django 5.1.4 on 2025-01-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_supp_id_stock_sell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.sell_product'),
        ),
    ]
